class DuplicateEmailError(Exception): ...
class InvalidCredentialsError(Exception): ...
class ConcertNotFoundError(Exception): ...
class InsufficientSeatsError(Exception): ...
class BookingNotFoundError(Exception): ...
class BookingCancelError(Exception): ...
